### ISSUE TITLE
run-local.sh not working

### ISSUE THREAD

**Issue by Meowcat285** [ikreymer/netcapsule#29]
The run-local.sh does not work and gives the error below.
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named yaml
./run-local.sh: line 5: docker-compose: command not found
./run-local.sh: line 6: docker-compose: command not found
`

**Comment by giser** [comment]
> The run-local.sh does not work and gives the error below.
> `Traceback (most recent call last): File "<string>", line 1, in <module> ImportError: No module named yaml ./run-local.sh: line 5: docker-compose: command not found ./run-local.sh: line 6: docker-compose: command not found `

`pip install pyyaml`
